/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter from being checked.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as AtividadeActivityIdRouteImport } from './routes/atividade.$activityId'
import { Route as ImprimirIndexRouteImport } from './routes/imprimir.index'
import { Route as ImprimirSheetIdRouteImport } from './routes/imprimir.$sheetId'
import { Route as ImprimirAlfabetizacaoRouteImport } from './routes/imprimir.alfabetizacao'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AtividadesRoute = AtividadesRouteImport.update({ id: '/atividades', path: '/atividades', getParentRoute: () => rootRouteImport } as any)
const MateriaisRoute = MateriaisRouteImport.update({ id: '/materiais', path: '/materiais', getParentRoute: () => rootRouteImport } as any)
const ProgressoRoute = ProgressoRouteImport.update({ id: '/progresso', path: '/progresso', getParentRoute: () => rootRouteImport } as any)
const AtividadeActivityIdRoute = AtividadeActivityIdRouteImport.update({ id: '/atividade/$activityId', path: '/atividade/$activityId', getParentRoute: () => rootRouteImport } as any)
const ImprimirIndexRoute = ImprimirIndexRouteImport.update({ id: '/imprimir/', path: '/imprimir/', getParentRoute: () => rootRouteImport } as any)
const ImprimirSheetIdRoute = ImprimirSheetIdRouteImport.update({ id: '/imprimir/$sheetId', path: '/imprimir/$sheetId', getParentRoute: () => rootRouteImport } as any)
const ImprimirAlfabetizacaoRoute = ImprimirAlfabetizacaoRouteImport.update({ id: '/imprimir/alfabetizacao', path: '/imprimir/alfabetizacao', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/materiais': typeof MateriaisRoute
  '/progresso': typeof ProgressoRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/imprimir/$sheetId': typeof ImprimirSheetIdRoute
  '/imprimir/': typeof ImprimirIndexRoute
  '/imprimir/alfabetizacao': typeof ImprimirAlfabetizacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/materiais': typeof MateriaisRoute
  '/progresso': typeof ProgressoRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/imprimir/$sheetId': typeof ImprimirSheetIdRoute
  '/imprimir': typeof ImprimirIndexRoute
  '/imprimir/alfabetizacao': typeof ImprimirAlfabetizacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/materiais': typeof MateriaisRoute
  '/progresso': typeof ProgressoRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/imprimir/$sheetId': typeof ImprimirSheetIdRoute
  '/imprimir/': typeof ImprimirIndexRoute
  '/imprimir/alfabetizacao': typeof ImprimirAlfabetizacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atividades' | '/materiais' | '/progresso' | '/atividade/$activityId' | '/imprimir/$sheetId' | '/imprimir/' | '/imprimir/alfabetizacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atividades' | '/materiais' | '/progresso' | '/atividade/$activityId' | '/imprimir/$sheetId' | '/imprimir' | '/imprimir/alfabetizacao'
  id: '__root__' | '/' | '/atividades' | '/materiais' | '/progresso' | '/atividade/$activityId' | '/imprimir/$sheetId' | '/imprimir/' | '/imprimir/alfabetizacao'
  fileRoutesById: FileRoutesById
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/atividades': { id: '/atividades'; path: '/atividades'; fullPath: '/atividades'; preLoaderRoute: typeof AtividadesRouteImport; parentRoute: typeof rootRouteImport }
    '/materiais': { id: '/materiais'; path: '/materiais'; fullPath: '/materiais'; preLoaderRoute: typeof MateriaisRouteImport; parentRoute: typeof rootRouteImport }
    '/progresso': { id: '/progresso'; path: '/progresso'; fullPath: '/progresso'; preLoaderRoute: typeof ProgressoRouteImport; parentRoute: typeof rootRouteImport }
    '/atividade/$activityId': { id: '/atividade/$activityId'; path: '/atividade/$activityId'; fullPath: '/atividade/$activityId'; preLoaderRoute: typeof AtividadeActivityIdRouteImport; parentRoute: typeof rootRouteImport }
    '/imprimir/': { id: '/imprimir/'; path: '/imprimir'; fullPath: '/imprimir/'; preLoaderRoute: typeof ImprimirIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/imprimir/$sheetId': { id: '/imprimir/$sheetId'; path: '/imprimir/$sheetId'; fullPath: '/imprimir/$sheetId'; preLoaderRoute: typeof ImprimirSheetIdRouteImport; parentRoute: typeof rootRouteImport }
    '/imprimir/alfabetizacao': { id: '/imprimir/alfabetizacao'; path: '/imprimir/alfabetizacao'; fullPath: '/imprimir/alfabetizacao'; preLoaderRoute: typeof ImprimirAlfabetizacaoRouteImport; parentRoute: typeof rootRouteImport }
  }
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  MateriaisRoute: typeof MateriaisRoute
  ProgressoRoute: typeof ProgressoRoute
  AtividadeActivityIdRoute: typeof AtividadeActivityIdRoute
  ImprimirSheetIdRoute: typeof ImprimirSheetIdRoute
  ImprimirIndexRoute: typeof ImprimirIndexRoute
  ImprimirAlfabetizacaoRoute: typeof ImprimirAlfabetizacaoRoute
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AtividadesRoute,
  MateriaisRoute,
  ProgressoRoute,
  AtividadeActivityIdRoute,
  ImprimirSheetIdRoute,
  ImprimirIndexRoute,
  ImprimirAlfabetizacaoRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
